Translations and typo
swingerman/lovelace-fluid-level-background-card pull request #244
Opened 2023-03-30 13:11 UTC by el97

I included the Portuguese translations and fixed a minor typo.

2023-03-30 14:14 UTC, el97 commented
Build failed? What did I do wrong? 🤔

2023-03-31 19:44 UTC, swingerman approved these changes

2023-03-31 19:46 UTC, swingerman requested changes

2023-03-31 19:46 UTC, swingerman commented on src/localize/localize.ts
> +  pt-BR: pt-BR,
This seems to be invalid syntax

2023-03-31 20:13 UTC, merged