Update localize.ts
swingerman/lovelace-fluid-level-background-card pull request #302
Opened 2023-10-06 16:46 UTC by misa1515

2023-11-28 20:57 UTC, swingerman requested changes
It seems that you forgot to add the translation file.

2023-11-29 06:37 UTC, misa1515 commented
Hello,
normally (like for other projects) are attached (please see screenshot)
![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/61636045/0cc6fef0-14aa-4a9b-8399-5e343d21a947)

2023-11-29 16:30 UTC, swingerman commented on src/localize/localize.ts
> +import * as sk from './languages/sk.json';
This file doesn't exists

2023-11-29 16:50 UTC, misa1515 commented
understood, it is in 2nd pull request.
![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/61636045/1cb8f934-a79d-439f-a930-95899717a53c)
If you eplain me "how to", I can make it, in future at once.

2023-12-06 15:52 UTC, swingerman commented
Please create one PR with all the files included.

2024-12-03 16:35 UTC, swingerman approved these changes

2024-12-03 16:39 UTC, merged